import type { CurrencyConfig } from './types';

/** Bảng cấu hình tiền tệ hiện hành (mục 7.1). */
export const DEFAULT_CURRENCIES: readonly CurrencyConfig[] = Object.freeze([
  {
    currency_code: 'VND',
    currency_name: 'đồng',
    decimal_handling: 'IGNORE',
    decimal_scale: 0,
    decimal_allowed: false,
    minor_unit_singular: null,
    minor_unit_plural: null,
    active: true,
    currency_name_en: 'dong',
    currency_name_en_plural: 'dong',
    minor_unit_singular_en: null,
    minor_unit_plural_en: null,
  },
  {
    currency_code: 'USD',
    currency_name: 'đô la Mỹ',
    decimal_handling: 'READ',
    decimal_scale: 2,
    decimal_allowed: true,
    minor_unit_singular: 'cent',
    minor_unit_plural: 'cent',
    active: true,
    currency_name_en: 'US dollar',
    currency_name_en_plural: 'US dollars',
    minor_unit_singular_en: 'cent',
    minor_unit_plural_en: 'cents',
  },
  {
    currency_code: 'EUR',
    currency_name: 'euro',
    decimal_handling: 'READ',
    decimal_scale: 2,
    decimal_allowed: true,
    minor_unit_singular: 'cent',
    minor_unit_plural: 'cent',
    active: true,
    currency_name_en: 'euro',
    currency_name_en_plural: 'euros',
    minor_unit_singular_en: 'cent',
    minor_unit_plural_en: 'cents',
  },
  {
    currency_code: 'GBP',
    currency_name: 'bảng Anh',
    decimal_handling: 'READ',
    decimal_scale: 2,
    decimal_allowed: true,
    minor_unit_singular: 'penny',
    minor_unit_plural: 'pence',
    active: true,
    currency_name_en: 'pound',
    currency_name_en_plural: 'pounds',
    minor_unit_singular_en: 'penny',
    minor_unit_plural_en: 'pence',
  },
  {
    currency_code: 'JPY',
    currency_name: 'yên Nhật',
    decimal_handling: 'IGNORE',
    decimal_scale: 0,
    decimal_allowed: false,
    minor_unit_singular: null,
    minor_unit_plural: null,
    active: true,
    currency_name_en: 'yen',
    currency_name_en_plural: 'yen',
    minor_unit_singular_en: null,
    minor_unit_plural_en: null,
  },
  {
    currency_code: 'SGD',
    currency_name: 'đô la Singapore',
    decimal_handling: 'READ',
    decimal_scale: 2,
    decimal_allowed: true,
    minor_unit_singular: 'cent',
    minor_unit_plural: 'cent',
    active: true,
    currency_name_en: 'Singapore dollar',
    currency_name_en_plural: 'Singapore dollars',
    minor_unit_singular_en: 'cent',
    minor_unit_plural_en: 'cents',
  },
] as CurrencyConfig[]);
