import type { CurrencyConfig } from './types';

/** Bảng cấu hình tiền tệ hiện hành (mục 7.1). */
export const DEFAULT_CURRENCIES: readonly CurrencyConfig[] = Object.freeze([
  {
    currency_code: 'VND',
    currency_name: 'đồng',
    decimal_handling: 'IGNORE',
    decimal_scale: 0,
    decimal_allowed: false,
    minor_unit_singular: null,
    minor_unit_plural: null,
    active: true,
  },
  {
    currency_code: 'USD',
    currency_name: 'đô la Mỹ',
    decimal_handling: 'READ',
    decimal_scale: 2,
    decimal_allowed: true,
    minor_unit_singular: 'cent',
    minor_unit_plural: 'cent',
    active: true,
  },
  {
    currency_code: 'EUR',
    currency_name: 'euro',
    decimal_handling: 'READ',
    decimal_scale: 2,
    decimal_allowed: true,
    minor_unit_singular: 'cent',
    minor_unit_plural: 'cent',
    active: true,
  },
  {
    currency_code: 'GBP',
    currency_name: 'bảng Anh',
    decimal_handling: 'READ',
    decimal_scale: 2,
    decimal_allowed: true,
    minor_unit_singular: 'penny',
    minor_unit_plural: 'pence',
    active: true,
  },
  {
    currency_code: 'JPY',
    currency_name: 'yên Nhật',
    decimal_handling: 'IGNORE',
    decimal_scale: 0,
    decimal_allowed: false,
    minor_unit_singular: null,
    minor_unit_plural: null,
    active: true,
  },
  {
    currency_code: 'SGD',
    currency_name: 'đô la Singapore',
    decimal_handling: 'READ',
    decimal_scale: 2,
    decimal_allowed: true,
    minor_unit_singular: 'cent',
    minor_unit_plural: 'cent',
    active: true,
  },
] as CurrencyConfig[]);
